Django_CRM/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crm.urls')),
]

crm/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.homepage, name='home_page'),
    path('homepage_week', views.homepageweek, name='home_page_week'),
    path('homepage_late', views.homepagelate, name='home_page_late'),

    path('list_clients', views.list_clients, name='list_clients'),
    path('list_deals', views.list_deals, name='list_deals'),
    path('list_calls', views.list_calls, name='list_calls'),
    path('list_reminders', views.list_reminders, name='list_reminders'),

    path('create_client', views.create_client, name='create_client'),
    path('create_call', views.create_call, name='create_call'),
    path('create_deal', views.create_deal, name='create_deal'),
    path('create_reminder', views.create_reminder, name='create_reminder'),

    path('detail_call/<int:pk>', views.DetailCall.as_view(), name='detailed_call'),
    path('detail_client/<int:pk>', views.DetailClient.as_view(), name='detailed_client'),
    path('detail_deal/<int:pk>', views.DetailDeal.as_view(), name='detailed_deal'),
    path('detail_reminder/<int:pk>', views.DetailReminder.as_view(), name='detailed_reminder'),

    path('update_client/<int:pk>', views.ClientUpdate.as_view(), name='update_client'),
    path('update_call/<int:pk>', views.CallUpdate.as_view(), name='update_call'),
    path('update_deal/<int:pk>', views.DealUpdate.as_view(), name='update_deal'),
    path('update_reminder/<int:pk>', views.ReminderUpdate.as_view(), name='update_reminder'),

    path('delete_call/<int:pk>', views.CallDelete.as_view(), name='delete_call'),
    path('delete_deal/<int:pk>', views.DealDelete.as_view(), name='delete_deal'),
    path('delete_reminder/<int:pk>', views.ReminderDelete.as_view(), name='delete_reminder'),

    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

crm/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Client(models.Model):
    company = models.CharField('Название клиента', max_length=100)

    contact_name = models.CharField('ФИО ЛПР-а', max_length=150)
    position = models.CharField('Должность', max_length=100)
    phone = models.CharField('Телефон', max_length=100)
    email = models.EmailField('Е-мэил', blank=True)
    address = models.CharField('Адрес', max_length=255)
    commentary = models.TextField('Коментарии')
    publish = models.DateTimeField('Дата создания', default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='user_clients')

    def get_absolute_url(self):
        return f'/detail_client/{self.id}'

    def __str__(self):
        return self.company


class Deal(models.Model):
    client = models.ForeignKey(Client, related_name='deals', on_delete=models.CASCADE)
    commentary = models.TextField('Сделка')
    publish = models.DateField('Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return f'/detail_deal/{self.id}'


class Call(models.Model):
    client = models.ForeignKey(Client, related_name='calls', on_delete=models.CASCADE)
    commentary = models.TextField('Коментарии')
    publish = models.DateField('Дата создания')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return f'/detail_call/{self.id}'


class Reminder(models.Model):
    client = models.ForeignKey(Client, related_name='reminders', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    CHOISE_EVENT = (
        ('call', 'Звонок'),
        ('deal', 'Сделка'),
        ('meeting', 'Встреча'),
    )
    event_type = models.CharField(max_length=50, choices=CHOISE_EVENT)
    commentary = models.TextField('Коментарии')
    deadline = models.DateTimeField('Сроки')

    def get_absolute_url(self):
        return f'/detail_reminder/{self.id}'

crm/forms.py
from .models import Client, Call, Deal, Reminder
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['company',
                  'contact_name',
                  'position',
                  'phone',
                  'email',
                  'address',
                  'commentary',
                  'publish']
        widgets = {
            'company': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Название клиента'
            }),
            'contact_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'ФИО ЛПРа'
            }),
            'position': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Должность ЛПРа'
            }),
            'phone': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Тел. номер'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'EMAIL'
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Адрес производства'
            }),
            'commentary': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Комментарии'
            }),
            'publish': forms.DateTimeInput(attrs={
                'class': 'form-control',
            }),

        }


class CallForm(forms.ModelForm):
    class Meta:
        model = Call
        fields = ['client',
                  'commentary',
                  'publish']
        widgets = {
            'commentary': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Комментарии'
            }),
            'publish': forms.DateInput(attrs={
                'autocomplete': 'off',
                'class': 'form-control',
            }),
        }


class ReminderForm(forms.ModelForm):
    class Meta:
        model = Reminder
        fields = ['client',
                  'event_type',
                  'commentary',
                  'deadline',
                  ]
        widgets = {
            'commentary': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Комментарии'
            }),
            'deadline': forms.DateTimeInput(attrs={
                    'autocomplete': 'off',
                    'placeholder': 'Дата напоминания'
            }),
        }


class DealForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = ['client',
                  'commentary',
                  'publish',
                  ]
        widgets = {
            'commentary': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Комментарии'
            }),
            'publish': forms.DateInput(attrs={
                'autocomplete': 'off',
                'class': 'form-control datetimepicker-input',
                'data-target': '#datetimepicker1'
            }),
        }


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    email = forms.EmailInput()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class DateForm(forms.Form):
    date = forms.DateTimeField(input_formats=['%d/%m/%Y %H:%M'])

crm/views.py
from django.utils import timezone
from django.shortcuts import render, redirect
from . import models
from . import forms
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import FormView


def list_clients(request):
    clients = models.Client.objects.all()
    return render(request, 'crm/list_clients.html', {'clients': clients})


@login_required
def list_calls(request):
    calls = models.Call.objects.order_by('publish')
    return render(request, 'crm/list_calls.html', {'calls': calls})


def list_reminders(request):
    reminders = models.Reminder.objects.order_by('deadline')
    return render(request, 'crm/list_reminders.html', {'reminders': reminders})


def list_deals(request):
    deals = models.Deal.objects.order_by('publish')
    return render(request, 'crm/list_deals.html', {'deals': deals})


class DetailClient(DetailView):
    model = models.Client
    template_name = 'crm/detailed_client.html'
    context_object_name = 'client'


class DetailCall(DetailView):
    model = models.Call
    template_name = 'crm/detailed_call.html'
    context_object_name = 'call'


class DetailDeal(DetailView):
    model = models.Deal
    template_name = 'crm/detailed_deal.html'
    context_object_name = 'deal'


class DetailReminder(DetailView):
    model = models.Reminder
    template_name = 'crm/detailed_reminder.html'
    context_object_name = 'reminder'


@login_required
def create_client(request):
    error = ''
    if request.method == 'POST':
        form = forms.ClientForm(request.POST)
        if form.is_valid():
            new_client = form.save(commit=False)
            new_client.author = request.user
            new_client.save()
            return redirect('list_clients')
        else:
            error = 'Форма заполнена неверно'
    form = forms.ClientForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'crm/create_client.html', data)


@login_required
def create_call(request):
    error = ''
    if request.method == 'POST':
        form = forms.CallForm(request.POST)
        if form.is_valid():
            new_call = form.save(commit=False)
            new_call.author = request.user
            new_call.save()
            return redirect('list_calls')
        else:
            error = 'Форма заполнена неверно'
    form = forms.CallForm()

    data = {
        'form': form,
        'error': error
    }
    return render(request, 'crm/create_call.html', data)


@login_required
def create_deal(request):
    error = ''
    if request.method == 'POST':
        form = forms.DealForm(request.POST)
        if form.is_valid():
            new_deal = form.save(commit=False)
            new_deal.author = request.user
            new_deal.save()
            return redirect('list_deals')
        else:
            error = 'Форма заполнена неверно'
    form = forms.DealForm()

    data = {
        'form': form,
        'error': error
    }
    return render(request, 'crm/create_deal.html', data)


@login_required
def create_reminder(request):
    error = ''
    if request.method == 'POST':
        form = forms.ReminderForm(request.POST)
        if form.is_valid():
            new_reminder = form.save(commit=False)
            new_reminder.author = request.user
            new_reminder.save()
            return redirect('list_reminders')
        else:
            error = 'Форма заполнена неверно'
    form = forms.ReminderForm()

    data = {
        'form': form,
        'error': error
    }
    return render(request, 'crm/create_reminder.html', data)


class RegisterUser(FormView):
    form_class = forms.RegistrationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

    def form_valid(self, form):
        form.save()
        return super(RegisterUser, self).form_valid(form)


class ClientUpdate(UpdateView):
    model = models.Client
    template_name = 'crm/create_client.html'
    form_class = forms.ClientForm


class CallUpdate(UpdateView):
    model = models.Call
    template_name = 'crm/create_call.html'
    form_class = forms.CallForm


class DealUpdate(UpdateView):
    model = models.Deal
    template_name = 'crm/create_deal.html'
    form_class = forms.DealForm


class ReminderUpdate(UpdateView):
    model = models.Reminder
    template_name = 'crm/create_reminder.html'
    form_class = forms.ReminderForm


class CallDelete(DeleteView):
    model = models.Call
    template_name = 'crm/delete_page.html'
    success_url = reverse_lazy('list_calls')


class DealDelete(DeleteView):
    model = models.Deal
    template_name = 'crm/delete_page.html'
    success_url = reverse_lazy('list_deals')


class ReminderDelete(DeleteView):
    model = models.Reminder
    template_name = 'crm/delete_page.html'
    success_url = reverse_lazy('list_reminders')


def homepage(request):
    text = "Планы на сегодня"
    startdate = timezone.now()
    enddate = startdate + timezone.timedelta(days=1)

    reminders = models.Reminder.objects.filter(deadline__range=[startdate, enddate])
    data = {
        'text': text,
        'reminders': reminders,
        'startdate': startdate,
    }
    return render(request, 'crm/homepage.html', data)


def homepageweek(request):
    text = "Планы на неделю"
    startdate = timezone.now()
    enddate = startdate + timezone.timedelta(days=7)
    reminders = models.Reminder.objects.filter(deadline__range=[startdate, enddate]).order_by('deadline')
    data = {
        'text': text,
        'reminders': reminders,
        'startdate': startdate,
    }
    return render(request, 'crm/homepage.html', data)


def homepagelate(request):
    text = "Просроченые события!"
    startdate = timezone.now()
    sdate = startdate - timezone.timedelta(days=14)
    enddate = startdate + timezone.timedelta(days=7)

    reminders = models.Reminder.objects.filter(deadline__range=[sdate, startdate]).order_by('deadline')
    data = {
        'text': text,
        'reminders': reminders,
        'startdate': startdate,
    }
    return render(request, 'crm/homepage.html', data)

crm/templates/crm/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <div class="header">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'crm/css/base.css' %}">
    <img src="{% static 'crm/img/logo_crm.png' %}" alt="logo">
        <ul>
            <a href="{% url 'home_page' %}"><li><i class="fas fa-home"></i>Главная</li></a>
            <a href="{% url 'list_clients' %}"><li><i class="fas fa-home"></i>Список клиентов</li></a>
            <a href="{% url 'list_deals' %}"><li><i class="fab fa-themeisle"></i>Все сделки</li></a>
            <a href="{% url 'list_calls' %}"><li><i class="fab fa-themeisle"></i>Все звонки</li></a>
            <a href="{% url 'list_reminders' %}"><li><i class="fab fa-themeisle"></i>Все напоминания</li></a>
        </ul>
    <ul class="login">
    {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}"><li class="loginli"><i>LOGOUT </i>| {{ user }}</li></a>
            {% else %}
                <a href="{% url 'login' %}"><li class="loginli">Войти</a> | <a href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
    </ul>

    </div>

</head>

<body>
    <div class="wrapper">


    <div class="content">
    {% block content %}{% endblock %}
    </div>

    <div class="sidebar">
    {% block deals %} {% endblock %}
    </div>

    <div class="sidebar1">
    {% block calls %} {% endblock %}
    </div>

    <div class="sidebar2">
    {% block plans %}  {% endblock %}
    </div>


    </div>
</body>
</html>

crm/templates/crm/base_two.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <div class="header">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>


<!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>


  <script>
    $(function () {
      $("#datetimepicker").datetimepicker();
    });
  </script>


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'crm/css/base.css' %}">
        <img src="{% static 'crm/img/logo_crm.png' %}" alt="logo">
        <ul>
            <a href="{% url 'home_page' %}"><li><i class="fas fa-home"></i>Главная</li></a>
            <a href="{% url 'list_clients' %}"><li><i class="fas fa-home"></i>Список клиентов</li></a>
            <a href="{% url 'list_deals' %}"><li><i class="fab fa-themeisle"></i>Все сделки</li></a>
            <a href="{% url 'list_calls' %}"><li><i class="fab fa-themeisle"></i>Все звонки</li></a>
            <a href="{% url 'list_reminders' %}"><li><i class="fab fa-themeisle"></i>Все напоминания</li></a>

        </ul>
    <ul class="login">
    {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}"><li class="loginli"><i>LOGOUT </i>| {{ user }}</li></a>
            {% else %}
                <a href="{% url 'login' %}"><li class="loginli">Войти</a> | <a href="{% url 'register' %}">Регистрация</a></li>
            {% endif %}
    </ul>
    </div>
</head>

<body>
    <div class="wrapper">


    <div class="content1">
    {% block content %}

    {% endblock %}
    </div>
    </div>
</body>
</html>

crm/templates/crm/create_call.html
{% extends 'crm/base_two.html' %}

{% block title %}
    Форма добавления клиента
{% endblock %}

{% block content  %}
    <h1>План звонка</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.client }}<br><br>
        {{ form.commentary }}<br>
        {{ form.publish }}
        <script>
        $(function () {
         $("#id_publish").datetimepicker({
             format: 'd.m.Y',
         });
         });
        </script>
        <br>
        <span>{{ error }}</span>

        <button class="btn btn-success" type="submit">Добавить</button>
    </form>

{% endblock %}

crm/templates/crm/create_client.html
{% extends 'crm/base_two.html' %}

{% block title %}
    Форма добавления клиента
{% endblock %}

{% block content  %}
    <h1>Форма добавления клиента</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.company }}<br>
        {{ form.contact_name }}<br>
        {{ form.position }}<br>
        {{ form.phone }}<br>
        {{ form.email }}<br>
        {{ form.address }}<br>
        {{ form.commentary }}<br>
        {{ form.publish }}<br>
        <span>{{ error }}</span>

        <button class="btn btn-success" type="submit">Добавить клиента</button>
    </form>

{% endblock %}

crm/templates/crm/create_deal.html
{% extends 'crm/base_two.html' %}

{% block title %}
    Форма добавления сделки
{% endblock %}

{% block content  %}
    <h1>Добавить сделку</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.client }}<br><br>
        {{ form.commentary }}<br>
        {{ form.publish }}
        <script>
        $(function () {
         $("#id_publish").datetimepicker({
             format: 'd.m.Y',
         });
         });
        </script>


        <br>
        <span>{{ error }}</span>

        <button class="btn btn-success" type="submit">Добавить</button>
    </form>

{% endblock %}

crm/templates/crm/detailed_call.html
{% extends 'crm/base.html' %}

{% block title %}
    {{ client.client_name}}
{% endblock %}

{% block content  %}
    <ul1>
    <a href="{% url 'update_call' call.id %}"><li><button class="btn btn-info" type="submit">Обновить данные</button></li></a>
    <a href="{% url 'delete_call' call.id %}"><li><button class="btn btn-info" type="submit">Удалить данные</button></li></a>
    </ul1><br><br>

        <h2>{{ call.client}} </h2>
        <hr>
    <p> Звонок </p>
    <p> Информация: {{ call.commentary}} </p>
    <p> Дата звонка: {{ call.publish}} </p>
    <p> АВТОР : {{ call.author }}</p>


{% endblock %}

crm/templates/crm/detailed_client.html
{% extends 'crm/base.html' %}

{% block title %}
    {{ client.company }}
{% endblock %}

{% block content  %}
    <ul1>
    <a href="{% url 'update_client' client.id %}"><li><button class="btn btn-info" type="submit">Обновить данные</button></li></a>
    </ul1><br><br>

    <table class="table1">
    <h2> {{ client.company }} </h2>
    <tr class="line"><th>ЛПР</th><td>{{ client.contact_name }}</td></tr>
    <tr class="line"><th>Должность</th><td>{{ client.position}}</td></tr>
    <tr class="line"><th>Контактный номер</th><td>{{ client.phone }}</td></tr>
    <tr class="line"><th>Email</th><td>{{ client.email}}</td></tr>
    <tr class="line"><th>Адрес производства</th><td>{{ client.address }}</td></tr>
    <tr class="line"><th>Информация</th><td>{{ client.commentary}}</td></tr>
    <tr class="line"><th>Автор</th><td>{{ client.author}}</td></tr>

    </table>
    {% endblock %}




    {% block calls %}
        <ul1>
    <a href="{% url 'create_call' %}"><li><button class="btn btn-info" type="submit">Добавить звонок</button></li></a>
    </ul1><br><br>


        <h4>История звонков</h4>
        <hr>

        <table class="table1">
    {% for el in client.calls.order_by %}
            <tr class="line1"> <th>{{ el.commentary | truncatewords:4}}</th></tr>
            <tr class="line1"> <th>{{ el.publish }}</th></tr>
            <tr class="line1"><th><a href="{% url 'detailed_call' el.id %}"> Подробнее </a><hr></th></tr>
    {% endfor %}
        </table>

    {% endblock %}





    {% block deals  %}
        <ul1>
    <a href="{% url 'create_deal' %}"><li><button class="btn btn-info" type="submit">Добавить сделку</button></li></a>
    </ul1><br><br>
        <h4>История сделок</h4>
        <hr>

        <table class="table1">
    {% for el in client.deals.order_by %}
            <tr class="line1"> <th>{{ el.commentary | truncatewords:4}}</th></tr>
            <tr class="line1"> <th>{{ el.publish }}</th></tr>
            <tr class="line1"><th><a href="{% url 'detailed_deal' el.id %}"> Подробнее </a><hr></th></tr>
    {% endfor %}
        </table>




    {% endblock  %}

    {% block plans  %}
        <ul1>
    <a href="{% url 'create_reminder' %}"><li><button class="btn btn-info" type="submit">Добавить напоминание</button></li></a>
    </ul1><br><br>
        <h4>Планы событий</h4>
        <hr>


        <table class="table1">
    {% for el in client.reminders.order_by %}
            <tr class="line1"> <th>{{ el.get_event_type_display}}</th></tr>
            <tr class="line1"> <th>{{ el.commentary | truncatewords:4}}</th></tr>
            <tr class="line1"> <th>{{ el.deadline }}</th></tr>
            <tr class="line1"><th><a href="{% url 'detailed_reminder' el.id %}"> Подробнее </a><hr></th></tr>
    {% endfor %}
        </table>
    {% endblock  %}

crm/templates/crm/detailed_reminder.html
{% extends 'crm/base.html' %}

{% block title %}
    {{ reminder.client_name}}
{% endblock %}

{% block content  %}
    <ul1>
    <a href="{% url 'update_reminder' reminder.id %}"><li><button class="btn btn-info" type="submit">Обновить данные</button></li></a>
    <a href="{% url 'delete_reminder' reminder.id %}"><li><button class="btn btn-info" type="submit">Удалить данные</button></li></a>
    </ul1><br><br>


    <h2>{{ reminder.client}} </h2>
        <hr>

    <p> Событие: {{ reminder.get_event_type_display }}</p>
    <p> Информация: {{ reminder.commentary}} </p>
    <p> Дата звонка: {{ reminder.deadline}} </p>
    <p> АВТОР : {{ reminder.author }}</p>


{% endblock %}

crm/templates/crm/homepage.html
{% extends 'crm/base_two.html' %}


{% block title %}
    Homepage
{% endblock %}


{% block content  %}
    <ul1>
    <a href="{% url 'home_page' %}"><li><button class="btn btn-info" type="submit">Планы на сегодня</button></li></a>
    <a href="{% url 'home_page_week' %}"><li><button class="btn btn-info" type="submit">Планы на неделю</button></li></a>
    <a href="{% url 'home_page_late' %}"><li><button class="btn btn-info" type="submit">Просроченные события</button></li></a>
    </ul1>
    <br>
    <p><h2>{{text}}</h2></p>
    Запланировано: {{ reminders.count }}
    {% if reminders.count == 1 %}
        событие
    {% elif reminders.count < 5 %}
        события
    {% else %}
        событий
    {% endif %}


    <table class="table2">
    <tbody>
    <tr class="line">
        <th>Клиент</th>
        <th>Событие</th>
        <th>Дата события</th>
        <th>Информация</th>
        <th>Автор</th>
        <th>подробней</th>
    </tr>
    {% for el in reminders %}
            <tr class="line">
            <td>{{ el.client }}</td>
            <td>{{ el.get_event_type_display }}</td>
            <td>{{ el.deadline }}</td>
            <td>{{ el.commentary | truncatewords:4}}</td>
            <td>{{ el.author }}</td>
            <td><a href="{% url 'detailed_reminder' el.id %}"> Подробнее </a></td>
            </tr>
    {% endfor %}
    </tbody>
    </table>



{% endblock %}

crm/templates/crm/list_reminders.html
{% extends 'crm/base_two.html' %}

{% block title %}
    Reminders
{% endblock %}


{% block content  %}
    <ul1>
    <a href="{% url 'create_reminder' %}"><li><button class="btn btn-info" type="submit">Создать напоминание</button></li></a>
    </ul1>
    <br>
    <br>
    <h2> Запланированные события </h2>

        <table class="table2">
    <tbody>
    <tr class="line">
        <th>Клиент</th>
        <th>Событие</th>
        <th>Дата события</th>
        <th>Коментарий</th>
        <th>Автор</th>
        <th>подробней</th>
    </tr>
    {% for el in reminders %}
        <tr class="line">
            <td>{{ el.client }}</td>
            <td>{{ el.get_event_type_display }}</td>
            <td>{{ el.deadline }}</td>
            <td>{{ el.commentary | truncatewords:4}}</td>
            <td>{{ el.author }}</td>
            <td><a href="{% url 'detailed_reminder' el.id %}"> Подробнее </a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>




{% endblock %}